<?php
/**
 * InspectionTypeSettingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InspectionTypeSettingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InspectionTypeSettingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productPlantInspTypeSettingGet
     *
     * Get entities from ProductPlantInspTypeSetting.
     *
     */
    public function testProductPlantInspTypeSettingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantInspTypeSettingInspectionLotTypeProductPlantGet
     *
     * Get entity from ProductPlantInspTypeSetting by key.
     *
     */
    public function testProductPlantInspTypeSettingInspectionLotTypeProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantInspTypeSettingInspectionLotTypeProductPlantPatch
     *
     * Update entity in ProductPlantInspTypeSetting.
     *
     */
    public function testProductPlantInspTypeSettingInspectionLotTypeProductPlantPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantInspTypeSettingInspectionLotTypeProductPlantProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductPlantInspTypeSettingInspectionLotTypeProductPlantProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantInspTypeSettingInspectionLotTypeProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantInspTypeSettingInspectionLotTypeProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantInspTypeSettingGet
     *
     * Get entities from related _ProductPlantInspTypeSetting.
     *
     */
    public function testProductPlantProductPlantProductPlantInspTypeSettingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantInspTypeSettingPost
     *
     * Add new entity to related _ProductPlantInspTypeSetting.
     *
     */
    public function testProductPlantProductPlantProductPlantInspTypeSettingPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
