<?php
/**
 * ProductPlantPurchaseTaxApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductPlantPurchaseTaxApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductPlantPurchaseTaxApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productPlantProductPlantProductPlantPurchaseTaxGet
     *
     * Get entities from related _ProductPlantPurchaseTax.
     *
     */
    public function testProductPlantProductPlantProductPlantPurchaseTaxGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantPurchaseTaxPost
     *
     * Add new entity to related _ProductPlantPurchaseTax.
     *
     */
    public function testProductPlantProductPlantProductPlantPurchaseTaxPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantPurchaseTaxGet
     *
     * Get entities from ProductPlantPurchaseTax.
     *
     */
    public function testProductPlantPurchaseTaxGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantPurchaseTaxProductPlantDepartureCountryGet
     *
     * Get entity from ProductPlantPurchaseTax by key.
     *
     */
    public function testProductPlantPurchaseTaxProductPlantDepartureCountryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantPurchaseTaxProductPlantDepartureCountryPatch
     *
     * Update entity in ProductPlantPurchaseTax.
     *
     */
    public function testProductPlantPurchaseTaxProductPlantDepartureCountryPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantPurchaseTaxProductPlantDepartureCountryProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductPlantPurchaseTaxProductPlantDepartureCountryProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantPurchaseTaxProductPlantDepartureCountryProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantPurchaseTaxProductPlantDepartureCountryProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
