<?php
/**
 * ProductDescriptionApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductDescriptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductDescriptionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productDescriptionGet
     *
     * Get entities from ProductDescription.
     *
     */
    public function testProductDescriptionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productDescriptionProductLanguageDelete
     *
     * Delete entity from ProductDescription.
     *
     */
    public function testProductDescriptionProductLanguageDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productDescriptionProductLanguageGet
     *
     * Get entity from ProductDescription by key.
     *
     */
    public function testProductDescriptionProductLanguageGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productDescriptionProductLanguagePatch
     *
     * Update entity in ProductDescription.
     *
     */
    public function testProductDescriptionProductLanguagePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productDescriptionProductLanguageProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductDescriptionProductLanguageProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productProductProductDescriptionGet
     *
     * Get entities from related _ProductDescription.
     *
     */
    public function testProductProductProductDescriptionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productProductProductDescriptionPost
     *
     * Add new entity to related _ProductDescription.
     *
     */
    public function testProductProductProductDescriptionPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
