<?php
/**
 * ProductEWMStorageTypeApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductEWMStorageTypeApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductEWMStorageTypeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productEWMStorageTypeGet
     *
     * Get entities from ProductEWMStorageType.
     *
     */
    public function testProductEWMStorageTypeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeDelete
     *
     * Delete entity from ProductEWMStorageType.
     *
     */
    public function testProductEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeGet
     *
     * Get entity from ProductEWMStorageType by key.
     *
     */
    public function testProductEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypePatch
     *
     * Update entity in ProductEWMStorageType.
     *
     */
    public function testProductEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeProductEWMWarehouseGet
     *
     * Get related _ProductEWMWarehouse.
     *
     */
    public function testProductEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeProductEWMWarehouseGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductEWMStorageTypeProductEWMWarehouseEntitledToDisposePartyEWMStorageTypeProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productEWMWarehouseProductEWMWarehouseEntitledToDisposePartyProductEWMStorageTypeGet
     *
     * Get entities from related _ProductEWMStorageType.
     *
     */
    public function testProductEWMWarehouseProductEWMWarehouseEntitledToDisposePartyProductEWMStorageTypeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productEWMWarehouseProductEWMWarehouseEntitledToDisposePartyProductEWMStorageTypePost
     *
     * Add new entity to related _ProductEWMStorageType.
     *
     */
    public function testProductEWMWarehouseProductEWMWarehouseEntitledToDisposePartyProductEWMStorageTypePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
