<?php
/**
 * ProductPlantStorageLocationApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductPlantStorageLocationApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductPlantStorageLocationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productPlantProductPlantProductPlantStorageLocationGet
     *
     * Get entities from related _ProductPlantStorageLocation.
     *
     */
    public function testProductPlantProductPlantProductPlantStorageLocationGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantStorageLocationPost
     *
     * Add new entity to related _ProductPlantStorageLocation.
     *
     */
    public function testProductPlantProductPlantProductPlantStorageLocationPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantStorageLocationGet
     *
     * Get entities from ProductPlantStorageLocation.
     *
     */
    public function testProductPlantStorageLocationGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantStorageLocationProductPlantStorageLocationGet
     *
     * Get entity from ProductPlantStorageLocation by key.
     *
     */
    public function testProductPlantStorageLocationProductPlantStorageLocationGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantStorageLocationProductPlantStorageLocationPatch
     *
     * Update entity in ProductPlantStorageLocation.
     *
     */
    public function testProductPlantStorageLocationProductPlantStorageLocationPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantStorageLocationProductPlantStorageLocationProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductPlantStorageLocationProductPlantStorageLocationProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantStorageLocationProductPlantStorageLocationProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantStorageLocationProductPlantStorageLocationProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
