<?php
/**
 * ProductUnitOfMeasureApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductUnitOfMeasureApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductUnitOfMeasureApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productProductProductUnitOfMeasureGet
     *
     * Get entities from related _ProductUnitOfMeasure.
     *
     */
    public function testProductProductProductUnitOfMeasureGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productProductProductUnitOfMeasurePost
     *
     * Add new entity to related _ProductUnitOfMeasure.
     *
     */
    public function testProductProductProductUnitOfMeasurePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberProductUnitOfMeasureGet
     *
     * Get related _ProductUnitOfMeasure.
     *
     */
    public function testProductUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberProductUnitOfMeasureGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureGet
     *
     * Get entities from ProductUnitOfMeasure.
     *
     */
    public function testProductUnitOfMeasureGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitDelete
     *
     * Delete entity from ProductUnitOfMeasure.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitGet
     *
     * Get entity from ProductUnitOfMeasure by key.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitPatch
     *
     * Update entity in ProductUnitOfMeasure.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANGet
     *
     * Get entities from related _ProductUnitOfMeasureEAN.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANPost
     *
     * Add new entity to related _ProductUnitOfMeasureEAN.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
