<?php
/**
 * ProductPlantApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductPlantApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductPlantApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productPlantCostingProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantCostingProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantForecastProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantForecastProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantGet
     *
     * Get entities from ProductPlant.
     *
     */
    public function testProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantInspTypeSettingInspectionLotTypeProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantInspTypeSettingInspectionLotTypeProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantInternationalTradeProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantInternationalTradeProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantMRPProductMRPAreaPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantMRPProductMRPAreaPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantPlanningProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantPlanningProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProcurementProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantProcurementProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantGet
     *
     * Get entity from ProductPlant by key.
     *
     */
    public function testProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantPatch
     *
     * Update entity in ProductPlant.
     *
     */
    public function testProductPlantProductPlantPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProdPlantInternationalTradeGet
     *
     * Get related _ProdPlantInternationalTrade.
     *
     */
    public function testProductPlantProductPlantProdPlantInternationalTradeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductPlantProductPlantProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantCostingGet
     *
     * Get related _ProductPlantCosting.
     *
     */
    public function testProductPlantProductPlantProductPlantCostingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantForecastGet
     *
     * Get related _ProductPlantForecast.
     *
     */
    public function testProductPlantProductPlantProductPlantForecastGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantInspTypeSettingGet
     *
     * Get entities from related _ProductPlantInspTypeSetting.
     *
     */
    public function testProductPlantProductPlantProductPlantInspTypeSettingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantInspTypeSettingPost
     *
     * Add new entity to related _ProductPlantInspTypeSetting.
     *
     */
    public function testProductPlantProductPlantProductPlantInspTypeSettingPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantMRPGet
     *
     * Get entities from related _ProductPlantMRP.
     *
     */
    public function testProductPlantProductPlantProductPlantMRPGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantMRPPost
     *
     * Add new entity to related _ProductPlantMRP.
     *
     */
    public function testProductPlantProductPlantProductPlantMRPPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantPlanningGet
     *
     * Get related _ProductPlantPlanning.
     *
     */
    public function testProductPlantProductPlantProductPlantPlanningGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantProcurementGet
     *
     * Get related _ProductPlantProcurement.
     *
     */
    public function testProductPlantProductPlantProductPlantProcurementGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantPurchaseTaxGet
     *
     * Get entities from related _ProductPlantPurchaseTax.
     *
     */
    public function testProductPlantProductPlantProductPlantPurchaseTaxGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantPurchaseTaxPost
     *
     * Add new entity to related _ProductPlantPurchaseTax.
     *
     */
    public function testProductPlantProductPlantProductPlantPurchaseTaxPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantQualityManagementGet
     *
     * Get related _ProductPlantQualityManagement.
     *
     */
    public function testProductPlantProductPlantProductPlantQualityManagementGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantSalesGet
     *
     * Get related _ProductPlantSales.
     *
     */
    public function testProductPlantProductPlantProductPlantSalesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantStorageGet
     *
     * Get related _ProductPlantStorage.
     *
     */
    public function testProductPlantProductPlantProductPlantStorageGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantStorageLocationGet
     *
     * Get entities from related _ProductPlantStorageLocation.
     *
     */
    public function testProductPlantProductPlantProductPlantStorageLocationGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantStorageLocationPost
     *
     * Add new entity to related _ProductPlantStorageLocation.
     *
     */
    public function testProductPlantProductPlantProductPlantStorageLocationPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantSupplyPlanningGet
     *
     * Get related _ProductPlantSupplyPlanning.
     *
     */
    public function testProductPlantProductPlantProductPlantSupplyPlanningGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantWorkSchedulingGet
     *
     * Get related _ProductPlantWorkScheduling.
     *
     */
    public function testProductPlantProductPlantProductPlantWorkSchedulingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantPurchaseTaxProductPlantDepartureCountryProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantPurchaseTaxProductPlantDepartureCountryProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantQualityManagementProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantQualityManagementProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantSalesProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantSalesProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantStorageLocationProductPlantStorageLocationProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantStorageLocationProductPlantStorageLocationProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantStorageProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantStorageProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantSupplyPlanningProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantSupplyPlanningProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantWorkSchedulingProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantWorkSchedulingProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productProductProductPlantGet
     *
     * Get entities from related _ProductPlant.
     *
     */
    public function testProductProductProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productProductProductPlantPost
     *
     * Add new entity to related _ProductPlant.
     *
     */
    public function testProductProductProductPlantPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
