<?php
/**
 * ProductPlantCostingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductPlantCostingApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductPlantCostingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productPlantCostingGet
     *
     * Get entities from ProductPlantCosting.
     *
     */
    public function testProductPlantCostingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantCostingProductPlantGet
     *
     * Get entity from ProductPlantCosting by key.
     *
     */
    public function testProductPlantCostingProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantCostingProductPlantPatch
     *
     * Update entity in ProductPlantCosting.
     *
     */
    public function testProductPlantCostingProductPlantPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantCostingProductPlantProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductPlantCostingProductPlantProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantCostingProductPlantProductPlantGet
     *
     * Get related _ProductPlant.
     *
     */
    public function testProductPlantCostingProductPlantProductPlantGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPlantProductPlantProductPlantCostingGet
     *
     * Get related _ProductPlantCosting.
     *
     */
    public function testProductPlantProductPlantProductPlantCostingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
