<?php
/**
 * ProductValuationAccountingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductValuationAccountingApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductValuationAccountingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productValuationAccountingGet
     *
     * Get entities from ProductValuationAccounting.
     *
     */
    public function testProductValuationAccountingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationAccountingProductValuationAreaValuationTypeGet
     *
     * Get entity from ProductValuationAccounting by key.
     *
     */
    public function testProductValuationAccountingProductValuationAreaValuationTypeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationAccountingProductValuationAreaValuationTypePatch
     *
     * Update entity in ProductValuationAccounting.
     *
     */
    public function testProductValuationAccountingProductValuationAreaValuationTypePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationAccountingProductValuationAreaValuationTypeProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductValuationAccountingProductValuationAreaValuationTypeProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationAccountingProductValuationAreaValuationTypeProductValuationGet
     *
     * Get related _ProductValuation.
     *
     */
    public function testProductValuationAccountingProductValuationAreaValuationTypeProductValuationGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationProductValuationAreaValuationTypeProductValuationAccountingGet
     *
     * Get related _ProductValuationAccounting.
     *
     */
    public function testProductValuationProductValuationAreaValuationTypeProductValuationAccountingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
