<?php
/**
 * ProductValuationLedgerPricesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductValuationLedgerPricesApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductValuationLedgerPricesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productValuationLedgerPricesGet
     *
     * Get entities from ProductValuationLedgerPrices.
     *
     */
    public function testProductValuationLedgerPricesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerGet
     *
     * Get entity from ProductValuationLedgerPrices by key.
     *
     */
    public function testProductValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerPatch
     *
     * Update entity in ProductValuationLedgerPrices.
     *
     */
    public function testProductValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerProductValuationGet
     *
     * Get related _ProductValuation.
     *
     */
    public function testProductValuationLedgerPricesProductValuationAreaValuationTypeCurrencyRoleLedgerProductValuationGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationProductValuationAreaValuationTypeProductValuationLedgerPricesGet
     *
     * Get entities from related _ProductValuationLedgerPrices.
     *
     */
    public function testProductValuationProductValuationAreaValuationTypeProductValuationLedgerPricesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productValuationProductValuationAreaValuationTypeProductValuationLedgerPricesPost
     *
     * Add new entity to related _ProductValuationLedgerPrices.
     *
     */
    public function testProductValuationProductValuationAreaValuationTypeProductValuationLedgerPricesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
