<?php
/**
 * ProductUnitOfMeasureEANApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product
 *
 * The service supports following operations: GET, POST, PUT, PATCH, DELETE. You can create, read, update, and delete product master data at the entity level.
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\ProductODV4\Test\Api;

use \BeLenka\SAP\ProductODV4\Configuration;
use \BeLenka\SAP\ProductODV4\ApiException;
use \BeLenka\SAP\ProductODV4\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductUnitOfMeasureEANApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\ProductODV4
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductUnitOfMeasureEANApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productUnitOfMeasureEANGet
     *
     * Get entities from ProductUnitOfMeasureEAN.
     *
     */
    public function testProductUnitOfMeasureEANGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberDelete
     *
     * Delete entity from ProductUnitOfMeasureEAN.
     *
     */
    public function testProductUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberGet
     *
     * Get entity from ProductUnitOfMeasureEAN by key.
     *
     */
    public function testProductUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberPatch
     *
     * Update entity in ProductUnitOfMeasureEAN.
     *
     */
    public function testProductUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberProductGet
     *
     * Get related _Product.
     *
     */
    public function testProductUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberProductGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberProductUnitOfMeasureGet
     *
     * Get related _ProductUnitOfMeasure.
     *
     */
    public function testProductUnitOfMeasureEANProductAlternativeUnitConsecutiveNumberProductUnitOfMeasureGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANGet
     *
     * Get entities from related _ProductUnitOfMeasureEAN.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANPost
     *
     * Add new entity to related _ProductUnitOfMeasureEAN.
     *
     */
    public function testProductUnitOfMeasureProductAlternativeUnitProductUnitOfMeasureEANPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
